# Define your constant variables


# RESPONSE CODE
RC_SUCCESS = 200
RC_BAD_REQUEST = 400
RC_NOT_FOUND = 404
RC_ERROR = 500

# RESPONSE MESSAGE
RM_SUCCESS = 'SUCCESS'
RM_BAD_REQUEST = 'BAD REQEUST'
RM_NOT_FOUND = 'NOT FOUND'
RM_ERROR = 'ERROR'